name: 'Snowmate Runner'
author: 'Snowmate'
description: 'Snowmate Runner'
inputs:
  github-token:
    description: 'GitHub Token'
    required: true
  project-path:
    description: 'Project Path'
    required: true
  project-id:
    description: 'Project ID'
    required: true
  client-id:
    description: 'Client ID'
    required: true
  secret-key:
    description: 'Secret Key'
    required: true
  api-url:
    description: 'API URL'
    required: false
  auth-url:
    description: 'Auth URL'
    required: false
  app-url:
    description: 'App URL'
    required: false
  disable-status-creation:
    description: 'Disable Status Creation'
    required: false
  additional-flags:
    description: 'Additional Flags'
    required: false
  pre-run-command:
    description: 'Pre Run Command'
    required: false
  pypi-url:
    description: 'PyPI URL'
    required: false
runs:
  using: 'node16'
  main: 'dist/index.js'
branding:
  icon: 'target'
  color: 'blue'
