name: "Snowmate Tests"
on:
  push:
jobs:
  run-tests:
    name: Run Tests
    runs-on: ubuntu-20.04
    steps:
      - name: "Git Checkout"
        uses: actions/checkout@v3
      - name: "Test Action"
        uses: ./regression
        with:
          project-path: ttt
          project-id: 123
          client-id: 1234
          secret-key: 555555
          repo-token: ${{ secrets.GITHUB_TOKEN }}
