name: 'Snowmate Tests'
on:
  push:
  pull_request:
jobs:
  run-tests:
    name: Snowmate Run Tests
    runs-on: ubuntu-20.04
    steps:
      - name: 'Git Checkout'
        uses: actions/checkout@v3
      # Project setup
      # - name: 'Python Setup'
      #   uses: actions/setup-python@v4
      #   with:
      #     python-version: '3.10'
      #     token: ${{ secrets.GITHUB_TOKEN }}
      #     cache: pip
      # - name: Install Pytest
      #   run: pip install pytest
      # - name: Install Snowmate Runner
      #   run: pip install -i "https://${{ secrets.SNOWMATE_CLIENT_ID }}:${{ secrets.SNOWMATE_SECRET_KEY }}@pypi.dev.snowmate.io/simple" -U snowmate_runner
      - name: 'Run Snowmate Tests'
        uses: ./
        with:
          project-path: .
          project-id: first-end2end
          client-id: ${{ secrets.SNOWMATE_CLIENT_ID }}
          secret-key: ${{ secrets.SNOWMATE_SECRET_KEY }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
